config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "/auth/twitter", as: :login
  get "/auth/twitter/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: :logout
  resources :users, only: [:show]
  resources :tweets, only: [:new, :create, :index]
  resources :favorites, only: [:create, :index]
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :twitter_service

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def twitter_service
    @twitter_service ||= TwitterService.new(current_user)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = twitter_service.all_favorites
  end

  def create
    twitter_service.add_favorite(params[:tweet_id])
    redirect_to favorites_path
  end

  # def destroy
  #   twitter_service.unfavorite(params[:tweet_id])
  #   redirect_to favorites_path
  # end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to current_user
  end

  def destroy
    session.clear
    redirect_to "/"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
  end

  def create
    twitter_service.tweet(params[:tweet][:text])
    redirect_to current_user
  end

  def index
    @tweets = twitter_service.my_tweets
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<ul class="collection">
  <% @favorites.each do |tweet| %>
    <li class="collection-item avatar card-radius">
      <%= image_tag tweet.user.profile_image_url, class: "card-radius" %>
      <span class="title"><%= tweet.user.name %></span>
      <p>@<%= tweet.user.handle %><br>
      <%= tweet.text %></p>
      <%= link_to favorites_path(tweet_id: tweet.id), method: :post, class: "secondary-content" do %>
        <i class="material-icons">grade</i>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/home/index.html.erb
<body class="home">
  <div class="center black-text">
    <% if current_user %>
      <p>Hi, <%= current_user.name %></p>
      <%= link_to "Logout", logout_path, class: "btn red black-text" %>
    <% else %>
      <h1>Carrier Pigeon</h1>
      <p>Stay in touch with , 139 characters at a time.</p>
      <%= link_to "Login with Twitter", login_path, class: "btn red black-text" %>
    <% end %>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WarPigeon</title>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link type="text/css" rel="stylesheet" href="stylesheets/materialize.css"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="stylesheets/application.css"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "partials/nav" %>
  <%= yield %>
</body>
</html>

app/views/partials/_nav.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper red">
      <a href="/" class="brand-logo center"><%= image_tag 'logo.png', class: "nav-logo" %></a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><%= link_to "Home", current_user, class: "black-text" %></li>
      </ul>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#" class="black-text">Your Profile</a></li>
        <li><%= link_to "Tweet!", new_tweet_path, class: "black-text" %></li>
        <% if current_user %>
          <li><%= link_to "Logout", logout_path, class: "black-text" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/partials/_profile_card.html.erb
<div class="card col s4 left card-radius">
  <p> <%= image_tag twitter_service.profile_img, class: "card-radius" %> </p>
  <h5><%= twitter_service.full_name %> </h5>
  <p> @<%= twitter_service.screen_name %> </p>

  <table class="centered">
    <thead>
      <tr>
        <th><%= link_to "Tweets", tweets_path %></th>
        <th>Following</th>
        <th>Followers</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= twitter_service.tweet_count %></td>
        <td><%= twitter_service.friend_count %></td>
        <td><%= twitter_service.follower_count %></td>
      </tr>
    </tbody>
</table>
</div>

app/views/partials/_tweet_cards.html.erb
<ul class="collection">
  <% twitter_service.feed.each do |tweet| %>
    <li class="collection-item avatar card-radius">
      <%= image_tag tweet.user.profile_image_url, class: "card-radius" %>
      <span class="title"><%= tweet.user.name %></span>
      <p>@<%= tweet.user.screen_name %><br>
      <%= tweet.text %></p>
      <%= link_to favorites_path(tweet_id: tweet.id), method: :post, class: "secondary-content" do %>
        <i class="material-icons">grade</i>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tweets/index.html.erb
<ul class="collection">
  <% @tweets.each do |tweet| %>
    <li class="collection-item avatar card-radius">
      <%= image_tag tweet.user.profile_image_url, class: "card-radius" %>
      <span class="title"><%= tweet.user.name %></span>
      <p>@<%= tweet.user.handle %><br>
      <%= tweet.text %></p>
      <%= link_to favorites_path(tweet_id: tweet.id), method: :post, class: "secondary-content" do %>
        <i class="material-icons">grade</i>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tweets/new.html.erb
<div class="container">
  <div class="card card-radius center">
    <%= form_tag tweets_path, method: :post do %>
      <%= label_tag "Compose a Tweet" %>
      <%= text_area_tag "tweet[text]" %>
      <%= submit_tag "Tweet", class: "btn red black-text" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render "partials/profile_card" %>
  <%= render "partials/tweet_cards" %>
</div>